// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGRt7UIqqCczV12VyoEaXMKmTrhqY5p08',
    appId: '1:698252299721:web:83e6f957c2b2d5d5886c18',
    messagingSenderId: '698252299721',
    projectId: 'moappclasswork9',
    authDomain: 'moappclasswork9.firebaseapp.com',
    storageBucket: 'moappclasswork9.appspot.com',
    measurementId: 'G-S665SMTZEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpgDr0Z9G2FuyNDUXxs-5sPIdC7CFHZhs',
    appId: '1:698252299721:android:a3d85f57a8c20d99886c18',
    messagingSenderId: '698252299721',
    projectId: 'moappclasswork9',
    storageBucket: 'moappclasswork9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRujSCM06MYFxJHjIjdHkCi80Upm0QzHM',
    appId: '1:698252299721:ios:3f0ee6fa3123e766886c18',
    messagingSenderId: '698252299721',
    projectId: 'moappclasswork9',
    storageBucket: 'moappclasswork9.appspot.com',
    iosClientId: '698252299721-aim0qk97fa3tvbog4lhbcd3hsgc1dgk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.classwork9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRujSCM06MYFxJHjIjdHkCi80Upm0QzHM',
    appId: '1:698252299721:ios:3f0ee6fa3123e766886c18',
    messagingSenderId: '698252299721',
    projectId: 'moappclasswork9',
    storageBucket: 'moappclasswork9.appspot.com',
    iosClientId: '698252299721-aim0qk97fa3tvbog4lhbcd3hsgc1dgk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.classwork9',
  );
}
